version: '3.3'

services:
  pg:
    container_name: go_pg
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=local
    ports:
      - 5432:5432
  rabbitmq:
    container_name: go_rabbit_mq
    image: rabbitmq:3.9.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=local
      - RABBITMQ_DEFAULT_PASS=local
      - RABBITMQ_DEFAULT_VHOST=local
    ports:
      - 5672:5672
      - 8080:15672
  mongo:
    container_name: go_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
    ports:
      - 27017:27017
networks:
  default:
    driver: "bridge"